version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tasksphere-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksphere
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasksphere-network

  redis:
    image: redis:7-alpine
    container_name: tasksphere-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - tasksphere-network

volumes:
  postgres_data:

networks:
  tasksphere-network:
    driver: bridge
